---
title: "Running the sql for one time use"
author: "Craig Demke"
date: "`r Sys.Date()`"
output: html_document
---

```{r set global chunks, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, message = FALSE
)
```

```{r load libraries}
library(tidyverse)
library(datasets)
library(plotly)
library(gt)
library(glue)
library(stringr)
library(DT)
library(purrr)
library(here)
library(lubridate)
library(utHelpR)
library(usheUtils)
library(readr)
library(janitor)
```

###  Here we pull the info from edify with the utHelp function
```{r}
financial_aid <- utHelpR::get_data_from_sql_file(file_name="financial_aid_file.sql",
                                               dsn="edify",
                                               context="project")
```

Here is a function that pulls in the data frame and the financial year

```{r}

fin_aid_file <- function(input_df, financial_aid_year) {
  output_df <- input_df %>% 
  filter(financial_aid_year_id == (financial_aid_year)) %>%
    mutate(term = substring(term, 5, 5)) %>%
    mutate(f_id = str_remove_all(f_id, "-")) %>% 
    mutate(banner_id = paste0("D", banner_id)) %>%
    mutate(f_id = case_when(
     f_id == "" ~ banner_id,
     TRUE ~ f_id)) %>% 
    select(-financial_aid_year_id)
  
return(output_df)
         
  }
```

check for duplicates 
```{r}
 check_for_duplicates <- fin_aid_file(financial_aid, '1819') %>% 
  get_dupes(inst_id, year, term, f_id, banner_id, financial_aid_type, financial_aid_amount) 

```

format to ushe for 2019
```{r}
write.table((fin_aid_file(financial_aid, '1819')), sep = "|", file = here::here("sensitive", "ut-fa-2019.txt"), row.names = FALSE, col.names = FALSE, quote = FALSE)
```

format to ushe for 2020
```{r}
write.table((fin_aid_file(financial_aid, '1920')), sep = "|", file = here::here("sensitive", "ut-fa-2020.txt"), row.names = FALSE, col.names = FALSE, quote = FALSE)
```

format to ushe for 2021
```{r}
write.table((fin_aid_file(financial_aid, '2021')), sep = "|", file = here::here("sensitive", "ut-fa-2021.txt"), row.names = FALSE, col.names = FALSE, quote = FALSE)
```

### Check your sensitive folder for the files